### ISSUE TITLE
About the raw image of Microsoft Demosaicing Dataset

### ISSUE THREAD

**Issue by fkmajiji** [mlvieras/demosaicing-dataset-generator#10]
Hello, mlvieras! I downloaded the Microsoft Demosaicing Dataset from https://www.microsoft.com/en-us/research/publication/joint-demosaicing-and-denoising-via-learned-non-parametric-random-fields/ , the readme.txt in zip file said there existed raw images of dataset, but I didnot found it, do you know where I can download the raw images?

**Comment by mlvieras** [comment]
Hi @fkmajiji. It's been a while since I worked with the dataset, but as far as I can tell, the dataset does not contain raw images, at least not in typical raw formats. It appears that they exported all the raw images as PNGs with only one channel. For instance see the directory `/MSR-Demosaicing/Dataset_LINEAR_with_noise/bayer_panasonic/input/` and you'll find a bunch of one-channel PNGs.

I'm not sure what you intend to do with them, but you should be able to use them as if they were raw for training or analysis.

Let me know if you have any more issues.
